version: "3"

name: joutonbad2-prod

volumes:
  mongo_data:

secrets:
  mongo_pwd:
    file: secrets/mongo_pwd
  api_secrets:
    file: secrets/api_secrets

services:
  mongo-primary2:
    container_name: mongo-primary2
    image: bitnami/mongodb:4.2.21
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-primary2
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    volumes:
      - mongo_data:/bitnami/mongodb
    ports:
      - 27019:27017
    secrets:
      - mongo_pwd

  mongo-secondary2:
    container_name: mongo-secondary2
    image: bitnami/mongodb:4.2.21
    depends_on:
      - mongo-primary2
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-secondary2
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongo-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    secrets:
      - mongo_pwd

  api2:
    container_name: api2
    build:
      context: ../../backend
      dockerfile: ./Dockerfile
    image: rec/joutonbad2-back
    restart: always
    environment:
      API_PORT: 3000
      SECRET_NAME: api_secrets
    ports:
      - 127.0.0.1:3001:3000
    secrets:
      - api_secrets
    depends_on:
      - mongo-primary2

  app2:
    container_name: app2
    build:
      context: ../../frontend
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: /api
        VITE_JOUTONBAD_CLIENT: REC Badminton
        VITE_AUTH0_MODERATOR_ROLE: moderator
        VITE_AUTH0_CLIENT_DOMAIN: recbadminton.eu.auth0.com
        VITE_AUTH0_CLIENT_ID: h5ZaQZStwE2IEFTILTInLheyr88SNIvb
        VITE_AUTH0_AUDIENCE: joutonbad-api
    image: rec/joutonbad2-front
    restart: always
    ports:
      - 127.0.0.1:8889:80
