version: "3"

name: joutonbad-prod

volumes:
  mongo_data:

secrets:
  mongo_pwd:
    file: secrets/mongo_pwd
  api_secrets:
    file: secrets/api_secrets

services:
  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:4.2.21
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    volumes:
      - mongo_data:/bitnami/mongodb
    ports:
      - 27018:27017
    secrets:
      - mongo_pwd

  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:4.2.21
    depends_on:
      - mongo-primary
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongo-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    secrets:
      - mongo_pwd

  api:
    container_name: api
    build:
      context: ../../backend
      dockerfile: ./Dockerfile
    image: rec/joutonbad-back
    restart: always
    environment:
      API_PORT: 3000
      SECRET_NAME: api_secrets
    ports:
      - 127.0.0.1:3000:3000
    secrets:
      - api_secrets
    depends_on:
      - mongo-primary

  app:
    container_name: app
    build:
      context: ../../frontend
      dockerfile: ./Dockerfile
      args:
        VITE_API_URL: /api
        VITE_MODERATOR_ROLE: tournois-api-editor
    image: rec/joutonbad-front
    restart: always
    ports:
      - 127.0.0.1:8888:80
