version: "3"

name: joutonbad-dev

volumes:
  mongo_data:

secrets:
  mongo_pwd:
    file: secrets/mongo_pwd
  api_secrets:
    file: secrets/api_secrets

services:
  mongo-primary-dev:
    container_name: mongo-primary-dev
    image: bitnami/mongodb:4.2.21
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-primary-dev
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    volumes:
      - mongo_data:/bitnami/mongodb
    ports:
      - 127.0.0.1:27019:27017
    secrets:
      - mongo_pwd

  mongo-secondary-dev:
    container_name: mongo-secondary-dev
    image: bitnami/mongodb:4.2.21
    depends_on:
      - mongo-primary-dev
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-secondary-dev
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongo-primary-dev
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_pwd
    secrets:
      - mongo_pwd

  api-dev:
    container_name: api-dev
    build:
      context: ../../backend
      dockerfile: ./Dockerfile
    image: rec/joutonbad-back-dev
    restart: always
    environment:
      API_PORT: 3000
      SECRET_NAME: api_secrets
    ports:
      - 127.0.0.1:3001:3000
    secrets:
      - api_secrets
    depends_on:
      - mongo-primary-dev

  app-dev:
    container_name: app-dev
    build:
      context: ../../frontend
      dockerfile: ./Dockerfile
    image: rec/joutonbad-front-dev
    restart: always
    ports:
      - 127.0.0.1:8889:80
