version: "3"

volumes:
  postgres_data:
  mongo_data:

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:14.9.0
    restart: always
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_PASSWORD: keycloakpwd

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:22.0.1
    restart: always
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpwd
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloakpwd
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  mongo:
    # https://github.com/prisma/prisma/issues/8266#issuecomment-966618742
    container_name: mongo
    image: bitnami/mongodb:4.2.21
    restart: always
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    volumes:
      - mongo_data:/bitnami/mongodb
    ports:
      - 27018:27017
