version: "3"

volumes:
  postgres_data:
  mongo_data:

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:14.9.0
    restart: always
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_PASSWORD: keycloakpwd

  keycloak:
    container_name: keycloak
    build:
      context: ../../keycloak
      dockerfile: ./Dockerfile
    image: joutonbad/keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpwd
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloakpwd
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  mongo-primary:
    container_name: mongo-primary
    image: bitnami/mongodb:4.2.21
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/bitnami/mongodb
    ports:
      - 27018:27017

  mongo-secondary:
    container_name: mongo-secondary
    image: bitnami/mongodb:4.2.21
    depends_on:
      - mongo-primary
    restart: always
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo-secondary
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongo-primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: root
